api:
    resource: "@ApiBundle/Controller/"
    type: annotation
    prefix:   /api

app:
    resource: '@AppBundle/Controller/'
    type: annotation
#    prefix: /{_locale}
#    requirements:
#        _locale: en|fr

logout:
    path: /logout