# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~



            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                default_target_path: /
                check_path: login
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manage, roles: ROLE_STAFF}
        - { path: ^/staff, roles: ROLE_STAFF}
        - { path: ^/customer, roles: [ROLE_USER, ROLE_STAFF]}
        - { path: ^/admin/*, roles: ROLE_ADMIN}
        - { path: ^/*, roles: ROLE_USER }

    role_hierarchy:
        ROLE_STAFF: [ROLE_USER]
        ROLE_ADMIN: [ ROLE_ALLOWED_TO_SWITCH]