<?php

namespace Wf3\ApiBundle\Repository;

/**
 * CenterRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CenterRequestRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCenterRequestByCenterAndId($centerCode, $centerRequestId)
    {
        return $this->createQueryBuilder('cr')
            ->select('cr')
            ->join('cr.center', 'c')
            ->where('cr.id = :center_request_id')
            ->setParameter('center_request_id', $centerRequestId)
            ->andWhere('c.code = :center_code')
            ->setParameter('center_code', $centerCode)
            ->getQuery()
            ->getResult()
            ;

    }

}
