<?php

namespace Wf3\ApiBundle\Repository;

/**
 * CenterRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CenterRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
