<?php

namespace Wf3\ApiBundle\Repository;

/**
 * ResponseRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
