<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Customer;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Customer $customer
     * @return mixed
     */
    public function findCustomerActiveCard(Customer $customer)
    {
        return $this->createQueryBuilder('c')
            ->join('c.customer', 'customer')
            ->where('c.customer = :customer')
            ->setParameter('customer', $customer)
            ->andWhere('c.active = :active')
            ->setParameter('active', true)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param $page
     * @param $max
     * @return Paginator
     */
    public function getAll($page, $max)
    {
        $qr = $this->createQueryBuilder('c')
            ->setFirstResult($max * ($page - 1))
            ->setMaxResults($max);
        return new Paginator($qr);
    }

    /**
     * @return mixed
     */
    public function countAll()
    {
        return $this->createQueryBuilder('c')
            ->select('COUNT(c)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
