<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Customer;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCustomerActiveCard(Customer $customer)
    {
        return $this->createQueryBuilder('c')
            ->join('c.customer', 'customer')
            ->where('c.customer = :customer')
            ->setParameter('customer', $customer)
            ->andWhere('c.active = :active')
            ->setParameter('active', true)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
