<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CenterRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $page
     * @param $max
     * @return Paginator
     */
    public function getAllWithPage($page, $max)
    {
        $qr = $this->createQueryBuilder('c')
            ->setFirstResult($max * ($page - 1))
            ->setMaxResults($max);

        return new Paginator($qr);
    }

    /**
     * @return mixed
     */
    public function countAll() {
        return $this->createQueryBuilder('c')
            ->select('COUNT(c)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
