<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Customer;

/**
 * CustomerOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOfferRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get all offers of one customer
     * @param Customer $customer
     */
    public function findCustomerOffers(Customer $customer)
    {
        $this->createQueryBuilder('co')
            ->join('co.offer', 'o')
            ->select('co, o')
            ->where('co.customer = :customer')->setParameter('customer', $customer)
            ->orderBy('co.id', 'DESC')
            ->getQuery()
            ->getResult();

    }
}
