<?php

namespace AppBundle\Repository;

/**
 * CustomerOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOfferRepository extends \Doctrine\ORM\EntityRepository
{
}
