<?php

namespace AppBundle\Repository;

/**
 * CustomerGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerGameRepository extends \Doctrine\ORM\EntityRepository
{
}
