<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Game;

/**
 * CustomerGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerGameRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCustomersByGame(Game $game)
    {
        return $this->createQueryBuilder('cg')
            ->join('cg.customer', 'c')
            ->select('cg, c')
            ->where('cg.game = :game')
            ->setParameter('game', $game)
            ->getQuery()
            ->getResult();
    }


}
