<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Customer;
use AppBundle\Entity\Offer;

/**
 * CustomerOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOfferRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get all offers of one customer
     * @param Customer $customer
     */
    public function findCustomerOffers(Customer $customer)
    {
        return $this->createQueryBuilder('co')
            ->join('co.offer', 'o')
            ->select('co, o')
            ->where('co.customer = :customer')->setParameter('customer', $customer)
            ->orderBy('co.id', 'DESC')
            ->getQuery()
            ->getResult();
    }


    public function getCountUnlockOffer(Customer $customer, Offer $offer)
    {
        return $this->createQueryBuilder('co')
                ->select('COUNT(co)')
                ->where('co.customer = :customer')
                ->setParameter('customer', $customer)
                ->andWhere('co.offer = :offer')
                ->setParameter('offer', $offer)
                ->getQuery()
                ->getSingleScalarResult();
    }
}
