<?php

namespace AppBundle\Repository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{

    public function getActiveOffers()
    {
        return $this->createQueryBuilder('o')
            ->where('o.expiredAt > CURRENT_TIMESTAMP() ')
            ->getQuery()
            ->getResult();
    }
}
