<?php

namespace AppBundle\Repository;

/**
 * RequestPasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestPasswordRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find request by token
     * @param $token
     * @return mixed
     */
    public function getRequestByToken($token)
    {
        return $this->createQueryBuilder('r')
                ->join('r.user', 'u')
                ->addSelect('u')
                ->where('r.token = :token')->setParameter('token', $token)
                ->getQuery()
                ->getOneOrNullResult();
    }
}
